- hosts: localhost
  # become: true
  tasks:
  - name: Update cache
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
  - include: tasks/neovim.yml 
  # - include: tasks/dotfiles.yml 
  # - include: tasks/zsh.yml 
  # - include: tasks/tmux.yml 
