- hosts: 127.0.0.1
  become: true
  tasks:
  - name: Update cache
    apt:
      force_apt_get: true
      update_cache: true
      state: present
  - include: tasks/neovim.yml 
  - include: tasks/dotfiles.yml 
  - include: tasks/zsh.yml 
  # - include: tasks/tmux.yml 
