- name: install stow
  ansible.builtin.apt:
    name: stow
    state: present
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/questionmorc/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    version: main
- name: Stow dotfiles
  become: false
  shell: cd $HOME/.dotfiled && stow .
