- name: Creates bin directory
  ansible.builtin.file:
    path: $HOME/.local/bin
    state: directory
- name: download neovim binary with checksum
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz
    checksum: sha256:44ee395d9b5f8a14be8ec00d3b8ead34e18fe6461e40c9c8c50e6956d643b6ca
    dest: /tmp/nvim-linux64.tar.gz
- name: Extract foo.tgz into /var/lib/foo
  ansible.builtin.unarchive:
    src: /tmp/nvim-linux64.tar.gz
    dest: $HOME/.local/bin
