---
- name: Create nvim directory
  ansible.builtin.file:
    path: /opt/nvim
    state: directory
- name: download neovim binary with checksum
  ansible.builtin.get_url:
    url: https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz
    checksum: sha256:44ee395d9b5f8a14be8ec00d3b8ead34e18fe6461e40c9c8c50e6956d643b6ca
    dest: /tmp/nvim-linux64.tar.gz
- name: Extract nvim binary
  ansible.builtin.unarchive:
    src: /tmp/nvim-linux64.tar.gz
    dest: /opt/
- name: Make executable
  ansible.builtin.file:
    path: /opt/nvim-linux64/bin/nvim
    mode: '0755'
- name: Create bin directory
  become: false
  ansible.builtin.file:
    path: $HOME/bin
    state: directory
- name: Symlink nvim
  become: false
  ansible.builtin.file:
    src: /opt/nvim-linux64/bin/nvim
    dest: $HOME/bin/nvim
    state: link
