---
- name: install packages
  ansible.builtin.apt:
    pkg: [stow, tmux, ripgrep, fd-find, gcc, unzip]
    state: present
- name: Cloning fzf
  become: false
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ lookup('env', 'HOME') }}/.fzf"
    recursive: true
    update: true
- name: Install fzf
  become: false
  shell: "{{ lookup('env', 'HOME') }}/.fzf/install --bin"
- name: Symlink fzf
  become: false
  ansible.builtin.file:
    src: $HOME/.fzf/bin/fzf
    dest: $HOME/bin/fzf
    state: link
- name: Symlink fzf-tmux
  become: false
  ansible.builtin.file:
    src: $HOME/.fzf/bin/fzf-tmux
    dest: $HOME/bin/fzf-tmux
    state: link

 # git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
# ~/.fzf/install
