---
- name: install packages
  ansible.builtin.apt:
    pkg: [stow, tmux, ripgrep, fd-find, gcc, unzip, git]
    state: present
- name: Create bin directory
  become: false
  ansible.builtin.file:
    path: $HOME/bin
    state: directory
- name: Cloning fzf
  become: false
  ansible.builtin.git:
    repo: https://github.com/junegunn/fzf.git
    dest: "{{ lookup('env', 'HOME') }}/.fzf"
    recursive: true
- name: Install fzf
  become: false
  shell: "{{ lookup('env', 'HOME') }}/.fzf/install --bin"
- name: Symlink fzf
  become: false
  ansible.builtin.file:
    src: $HOME/.fzf/bin/fzf
    dest: $HOME/bin/fzf
    state: link
- name: Symlink fzf-tmux
  become: false
  ansible.builtin.file:
    src: $HOME/.fzf/bin/fzf-tmux
    dest: $HOME/bin/fzf-tmux
    state: link
- name: Cloning zoxide
  become: false
  ansible.builtin.git:
    repo: https://github.com/ajeetdsouza/zoxide
    dest: "{{ lookup('env', 'HOME') }}/.zoxide"
    recursive: true
    update: true
    version: v0.9.4
- name: Install zoxide
  shell: "{{ lookup('env', 'HOME') }}/.zoxide/install.sh"
- name: Make zoxide installer executable
  become: false
  ansible.builtin.file:
    path: $HOME/.zoxide/install.sh
    mode: '0755'
- name: download oh-my-posh binary with checksum
  become: false
  ansible.builtin.get_url:
    url: https://github.com/JanDeDobbeleer/oh-my-posh/releases/download/v19.28.0/posh-linux-amd64
    checksum: sha256:D170EE6920627B64635D0B70AE46EBD90954655DA3A53DAE2E23CED4A49E8831
    dest: $HOME/bin/oh-my-posh
- name: Make oh-my-posh executable
  become: false
  ansible.builtin.file:
    path: $HOME/bin/oh-my-posh
    mode: '0755'
- name: gcloud-sdk
  become: false
  ansible.builtin.get_url:
    url: https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-cli-475.0.0-linux-x86_64.tar.gz
    checksum: sha256:dd5e035fb0ce7afeede98081ae808b9cfd0d3cc94279d202599b67b29ff2c386
    dest: /tmp/google-cloud-sdk.tar.gz
- name: Extract gcloud binary
  become: false
  ansible.builtin.unarchive:
    src: /tmp/google-cloud-sdk.tar.gz
    dest: $HOME/google-cloud-sdk

# install go
# install nvme
